import { motion } from "framer-motion";

const codeTexts = [
    ["const secret = '42';",
        "let isLoading = true;",
        "function hack() {",
        "  console.log('Access granted');",
        "  alert('System breached!');",
        "}",
        "if (user.isAdmin) {",
        "  enableRootAccess();",
        "}",
        "// TODO: patch vulnerability",
        "while(true) { /* infinite loop */ }",
        "const key = 'xyz123';",
        "// decrypting data...",
        "  _________________________",
        "     ||   ||     ||   ||",
        "     ||   ||, , ,||   ||",
        "     ||  (||/|/(\||/  ||",
        "     ||  ||| _'_`|||  ||",
        "     ||   || o o ||   ||",
        "     ||  (||  - `||)  ||",
        "     ||   ||  =  ||   ||",
        "     ||   ||\___/||   ||",
        "     ||___||) , (||___||",
        "    /||---||-\_/-||---||\\",
        "   / ||--_||_____||_--|| \\",
        "  (_(||)-| S123-45 |-(||)_)",],
    [
        "while(!freedom) {",
        "  try {",
        "    getFreedom()",
        "  } catch {",
        "    searchEvidence()",
        "  }",
        "}"
    ],
    ["const secret = '42';",
        "let isLoading = true;",
        "function hack() {",
        "  console.log('Access granted');",
        "  alert('System breached!');",
        "}",
        "if (user.isAdmin) {",
        "  enableRootAccess();",
        "}",
        "// TODO: patch vulnerability",
        "while(true) { /* infinite loop */ }",
        "const key = 'xyz123';",
        "// decrypting data...",
        "  _________________________",
        "     ||   ||     ||   ||",
        "     ||   ||, , ,||   ||",
        "     ||  (||/|/(\||/  ||",
        "     ||  ||| _'_`|||  ||",
        "     ||   || o o ||   ||",
        "     ||  (||  - `||)  ||",
        "     ||   ||  =  ||   ||",
        "     ||   ||\___/||   ||",
        "     ||___||) , (||___||",
        "    /||---||-\_/-||---||\\",
        "   / ||--_||_____||_--|| \\",
        "  (_(||)-| S123-45 |-(||)_)",],
    ["const secret = '42';",
        "let isLoading = true;",
        "function hack() {",
        "  console.log('Access granted');",
        "  alert('System breached!');",
        "}",
        "if (user.isAdmin) {",
        "  enableRootAccess();",
        "}",
        "// TODO: patch vulnerability",
        "while(true) { /* infinite loop */ }",
        "const key = 'xyz123';",
        "// decrypting data...",
        "  _________________________",
        "     ||   ||     ||   ||",
        "     ||   ||, , ,||   ||",
        "     ||  (||/|/(\||/  ||",
        "     ||  ||| _'_`|||  ||",
        "     ||   || o o ||   ||",
        "     ||  (||  - `||)  ||",
        "     ||   ||  =  ||   ||",
        "     ||   ||\___/||   ||",
        "     ||___||) , (||___||",
        "    /||---||-\_/-||---||\\",
        "   / ||--_||_____||_--|| \\",
        "  (_(||)-| S123-45 |-(||)_)",],
    ["const secret = '42';",
        "let isLoading = true;",
        "function hack() {",
        "  console.log('Access granted');",
        "  alert('System breached!');",
        "}",
        "if (user.isAdmin) {",
        "  enableRootAccess();",
        "}",
        "// TODO: patch vulnerability",
        "while(true) { /* infinite loop */ }",
        "const key = 'xyz123';",
        "// decrypting data...",
        "  _________________________",
        "     ||   ||     ||   ||",
        "     ||   ||, , ,||   ||",
        "     ||  (||/|/(\||/  ||",
        "     ||  ||| _'_`|||  ||",
        "     ||   || o o ||   ||",
        "     ||  (||  - `||)  ||",
        "     ||   ||  =  ||   ||",
        "     ||   ||\___/||   ||",
        "     ||___||) , (||___||",
        "    /||---||-\_/-||---||\\",
        "   / ||--_||_____||_--|| \\",
        "  (_(||)-| S123-45 |-(||)_)",],
    ["const secret = '42';",
        "let isLoading = true;",
        "function hack() {",
        "  console.log('Access granted');",
        "  alert('System breached!');",
        "}",
        "if (user.isAdmin) {",
        "  enableRootAccess();",
        "}",
        "// TODO: patch vulnerability",
        "while(true) { /* infinite loop */ }",
        "const key = 'xyz123';",
        "// decrypting data...",
        "  _________________________",
        "     ||   ||     ||   ||",
        "     ||   ||, , ,||   ||",
        "     ||  (||/|/(\||/  ||",
        "     ||  ||| _'_`|||  ||",
        "     ||   || o o ||   ||",
        "     ||  (||  - `||)  ||",
        "     ||   ||  =  ||   ||",
        "     ||   ||\___/||   ||",
        "     ||___||) , (||___||",
        "    /||---||-\_/-||---||\\",
        "   / ||--_||_____||_--|| \\",
        "  (_(||)-| S123-45 |-(||)_)",],
    ["const secret = '42';",
        "let isLoading = true;",
        "function hack() {",
        "  console.log('Access granted');",
        "  alert('System breached!');",
        "}",
        "if (user.isAdmin) {",
        "  enableRootAccess();",
        "}",
        "// TODO: patch vulnerability",
        "while(true) { /* infinite loop */ }",
        "const key = 'xyz123';",
        "// decrypting data...",
        "  _________________________",
        "     ||   ||     ||   ||",
        "     ||   ||, , ,||   ||",
        "     ||  (||/|/(\||/  ||",
        "     ||  ||| _'_`|||  ||",
        "     ||   || o o ||   ||",
        "     ||  (||  - `||)  ||",
        "     ||   ||  =  ||   ||",
        "     ||   ||\___/||   ||",
        "     ||___||) , (||___||",
        "    /||---||-\_/-||---||\\",
        "   / ||--_||_____||_--|| \\",
        "  (_(||)-| S123-45 |-(||)_)",],
    ["const secret = '42';",
        "let isLoading = true;",
        "function hack() {",
        "  console.log('Access granted');",
        "  alert('System breached!');",
        "}",
        "if (user.isAdmin) {",
        "  enableRootAccess();",
        "}",
        "// TODO: patch vulnerability",
        "while(true) { /* infinite loop */ }",
        "const key = 'xyz123';",
        "// decrypting data...",
        "  _________________________",
        "     ||   ||     ||   ||",
        "     ||   ||, , ,||   ||",
        "     ||  (||/|/(\||/  ||",
        "     ||  ||| _'_`|||  ||",
        "     ||   || o o ||   ||",
        "     ||  (||  - `||)  ||",
        "     ||   ||  =  ||   ||",
        "     ||   ||\___/||   ||",
        "     ||___||) , (||___||",
        "    /||---||-\_/-||---||\\",
        "   / ||--_||_____||_--|| \\",
        "  (_(||)-| S123-45 |-(||)_)",],

];

function CodeColumn({ lines, delay = 0 }: { lines: string[], delay: number }) {
    return (
        <motion.div
            className="flex flex-col text-green-400 font-mono text-xs select-none"
            animate={{ y: ["0%", "100%"] }}
            transition={{
                repeat: Infinity,
                duration: 10,
                ease: "linear",
                delay,
            }}
            style={{ whiteSpace: "pre" }}
        >
            {/* double le contenu pour le scroll infini */}
            {lines.concat(lines).map((line: string, i: number) => (
                <div key={i} className="leading-[1.1em]">
                    {line}
                </div>
            ))}
        </motion.div>
    );
}

export default function CodeBackground() {
    return (
        <div className="absolute inset-0 overflow-hidden bg-black opacity-30 pointer-events-none z-0 flex space-x-4 px-8 py-4">
            {codeTexts.map((lines, i) => (
                <CodeColumn key={i} lines={lines} delay={(10 / codeTexts.length) * i} />
            ))}
        </div>
    );
}